language: java
jdk:
  - oraclejdk13
matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      install:
        - curl -s "https://get.sdkman.io" | bash
        - source ~/.bash_profile
        - sdk install gradle
        - sdk install kotlin
        - npm install -g danger@7.1.4
        - sudo chmod -R a+rwx /usr/local/
      script:
        - cd kotlin
        - make install
        - cd ..
        - gradle wrapper
        - ./gradlew build
        - ./gradlew shadowJar
        - DEBUG='*' danger-kotlin ci