language: java
matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      install:
        - bash <(curl -s https://raw.githubusercontent.com/danger/kotlin/master/scripts/install.sh)
        - source ~/.bash_profile
      script:
        - gradle danger-kotlin-library:test
        - DEBUG='*' danger-kotlin ci