language: java
os: linux
dist: trusty
sudo: required

jobs:
  include:
    - stage: Build
      if: type = pull_request
      install:
        - curl -s "https://get.sdkman.io" | bash
        - source ~/.bash_profile
        - sdk install gradle
        - sdk install kotlin
        - npm install -g danger@7.1.4
        - sudo chmod -R a+rwx /usr/local/
      script:
        - cd kotlin
        - make install
        - cd ..
        - gradle wrapper
        - ./gradlew build
        - ./gradlew shadowJar
        - DEBUG='*' danger-kotlin ci
    - stage: Deploy
      if: type != pull_request
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          repo: gianluz/danger-kotlin-android-lint-plugin
          tags: true
          all_branches: true
          jdk: oraclejdk8