language: java
matrix:
  include:
    - os: osx
      osx_image: xcode10
      install:
        - curl -s "https://get.sdkman.io" | bash
        - source ~/.bash_profile
        - sdk install kscript
        - sdk install gradle
        - sdk install kotlin
        - npm install -g danger@7.1.4
      script:
        - make -C ./kotlin/Makefile install
        - gradle danger-kotlin-android-lint-plugin:test
        - DEBUG='*' danger-kotlin ci
